name: Notify on New Event

on:
  push:
    branches: [ main ]
    paths:
      - 'public/assets/blog/**'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Notify subscribers for newly added events only
        env:
          BASE_SHA: ${{ github.event.before }}
          HEAD_SHA: ${{ github.sha }}
          BUTTONDOWN_API_KEY: ${{ secrets.BUTTONDOWN_API_KEY }}
          SITE_URL: https://weiguangcui.github.io/DECAF/
        run: |
          node scripts/notify-new-events.mjs
